### ISSUE TITLE
HLA population resource for the published 1000 Swedish genomes

### ISSUE THREAD

**Issue by Nazeeefa** [slowkow/awesome-vdj#3]
Hi! 

Thank you for creating this repository. Is the following study relevant addition for this collection? :)

[SweHLA: the high confidence HLA typing bio-resource drawn from 1 000 Swedish genomes](https://www.nature.com/articles/s41431-019-0559-2)

**Comment by slowkow** [comment]
That's an interesting resource! Thank you for sharing.

Feel free to [contribute to the list](https://github.com/slowkow/awesome-vdj/blob/master/CONTRIBUTING.md). Or let me know if you prefer that I do it.

**Comment by Nazeeefa** [comment]
Cool. Pull request submitted.
